# Generated by Django 4.2.19 on 2025-08-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='recurrence_days',
            field=models.JSONField(blank=True, default=list, help_text='List of weekday numbers: 0=Monday, 1=Tuesday, ..., 6=Sunday'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recurrence_end_type',
            field=models.CharField(choices=[('no_end', 'No end time'), ('by_date', 'By date'), ('after_occurrences', 'After occurrences')], default='no_end', max_length=20),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1, help_text='Repeat every X weeks'),
        ),
        migrations.AddField(
            model_name='liveclass',
            name='recurrence_occurrences',
            field=models.PositiveIntegerField(blank=True, help_text='Number of occurrences after which to stop', null=True),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (Legacy field)', null=True),
        ),
    ]
