# Generated by Django 4.2.19 on 2025-08-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_liveclass_recurrence_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass',
            name='recurrence_days',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='recurrence_end_type',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='recurrence_interval',
        ),
        migrations.RemoveField(
            model_name='liveclass',
            name='recurrence_occurrences',
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday', null=True),
        ),
    ]
