# Generated by Django 4.2.19 on 2025-08-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_liveclass_recurrence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, help_text='List of days (0=Monday, 6=Sunday)'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='day_of_week',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday (deprecated, use days_of_week)', null=True),
        ),
    ]
