# Generated by Django 4.2.19 on 2025-08-28 06:26

from django.db import migrations


def migrate_day_of_week_to_days_of_week(apps, schema_editor):
    """
    Migrate existing day_of_week values to the new days_of_week JSONField
    """
    LiveClass = apps.get_model('api', 'LiveClass')
    
    for live_class in LiveClass.objects.all():
        if live_class.day_of_week is not None and not live_class.days_of_week:
            live_class.days_of_week = [live_class.day_of_week]
            live_class.save()


def reverse_migrate_days_of_week_to_day_of_week(apps, schema_editor):
    """
    Reverse migration: convert days_of_week back to day_of_week if only one day is selected
    """
    LiveClass = apps.get_model('api', 'LiveClass')
    
    for live_class in LiveClass.objects.all():
        if live_class.days_of_week and len(live_class.days_of_week) == 1:
            live_class.day_of_week = live_class.days_of_week[0]
            live_class.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_liveclass_days_of_week_alter_liveclass_day_of_week'),
    ]

    operations = [
        migrations.RunPython(
            migrate_day_of_week_to_days_of_week,
            reverse_migrate_days_of_week_to_day_of_week,
        ),
    ]
