# Generated by Django 4.2.19 on 2025-08-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20250828_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('meeting_id', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoomRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_meeting_id', models.CharField(max_length=255)),
                ('zoom_recording_id', models.CharField(max_length=255, unique=True)),
                ('zoom_meeting_uuid', models.CharField(max_length=255)),
                ('recording_start_time', models.DateTimeField()),
                ('recording_end_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(default='mp4', max_length=10)),
                ('zoom_download_url', models.URLField(max_length=500)),
                ('download_token', models.CharField(blank=True, max_length=255, null=True)),
                ('r2_storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('r2_storage_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.liveclass')),
                ('subject_recording_video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoom_recording', to='api.subjectrecordingvideo')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['zoom_meeting_id'], name='api_zoomrec_zoom_me_f6dd2b_idx'), models.Index(fields=['zoom_recording_id'], name='api_zoomrec_zoom_re_0c46a3_idx'), models.Index(fields=['status'], name='api_zoomrec_status_2ec315_idx')],
            },
        ),
    ]
