# Generated by Django 4.2.19 on 2025-08-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_zoomwebhooklog_zoomrecording'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoomrecording',
            name='live_class',
        ),
        migrations.RemoveField(
            model_name='zoomrecording',
            name='subject_recording_video',
        ),
        migrations.DeleteModel(
            name='ZoomWebhookLog',
        ),
        migrations.DeleteModel(
            name='ZoomRecording',
        ),
    ]
