# Generated by Django 4.2.19 on 2025-08-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_zoomwebhooklog_zoomrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomrecording',
            name='download_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
