# Generated by Django 4.2.19 on 2025-08-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_zoomrecording_download_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrecordingvideo',
            name='is_auto_created',
            field=models.BooleanField(default=False, help_text='True if this video was automatically created from Zoom recording'),
        ),
    ]
