# Generated by Django 4.2.19 on 2025-11-02 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0010_subjectrecordingvideo_is_auto_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_kind",
                    models.CharField(
                        choices=[("onepg", "OnePG"), ("nchl", "NCHL"), ("qr", "QR")],
                        max_length=10,
                    ),
                ),
                (
                    "payment_id",
                    models.IntegerField(help_text="Primary key of the payment record"),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "merchant_txn_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "invoice_pdf",
                    models.FileField(blank=True, null=True, upload_to="invoices/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NCHLPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("merchant_txn_id", models.CharField(max_length=100, unique=True)),
                (
                    "gateway_txn_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "NCHL Payment",
                "verbose_name_plural": "NCHL Payments",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ZoomAllowedHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Zoom host email address", max_length=254, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Host name for reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable recording processing for this host",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this host",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Zoom Allowed Host",
                "verbose_name_plural": "Zoom Allowed Hosts",
                "ordering": ["email"],
            },
        ),
        migrations.AddField(
            model_name="zoomrecording",
            name="host_email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the Zoom meeting host",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zoomwebhooklog",
            name="host_email",
            field=models.EmailField(
                blank=True,
                help_text="Email of the Zoom meeting host",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="zoomrecording",
            index=models.Index(
                fields=["host_email"], name="api_zoomrec_host_em_60bdf3_idx"
            ),
        ),
        migrations.AddField(
            model_name="nchlpayment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nchl_payments",
                to="api.course",
            ),
        ),
        migrations.AddField(
            model_name="nchlpayment",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nchl_payments",
                to="api.program",
            ),
        ),
        migrations.AddField(
            model_name="nchlpayment",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="nchl_payments", to="api.subject"
            ),
        ),
        migrations.AddField(
            model_name="nchlpayment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nchl_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billinghistory",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.course",
            ),
        ),
        migrations.AddField(
            model_name="billinghistory",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.program",
            ),
        ),
        migrations.AddField(
            model_name="billinghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
