"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab
from decouple import config
from dotenv import load_dotenv
from import_export.formats.base_formats import CSV, XLSX
from storages.backends.s3boto3 import S3Boto3Storage
from boto3.s3.transfer import TransferConfig
import dj_database_url

IMPORT_FORMATS = [CSV, XLSX]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wd2uua!lj6v#%a^9y65q@x+8u=pm=-0ij1!a7^s$=i2u2+!#g_'

# SECURITY WARNING: don't run with debug turned on in production!
# import secrets
# DEBUG = True
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*','localhost','api.k12nepal.com','www.api.k12nepal.com','ws.k12nepal.com','www.ws.k12nepal.com']

# SITE_URL = 'http://localhost:8000' 
SITE_URL = 'https://api.k12nepal.com' if DEBUG else 'http://localhost:8000'




load_dotenv()
 

ZOOM_ACESS_TOKEN = os.getenv('ZOOM_ACESS_TOKEN')


ZOOM_API_KEY = os.getenv("ZOOM_API_KEY")
ZOOM_API_SECRET = os.getenv("ZOOM_API_SECRET")

# Server-to-Server OAuth App for Recording Management
ZOOM_S2S_ACCOUNT_ID = config('ZOOM_S2S_ACCOUNT_ID', default='')
ZOOM_S2S_CLIENT_ID = config('ZOOM_S2S_CLIENT_ID', default='')
ZOOM_S2S_CLIENT_SECRET = config('ZOOM_S2S_CLIENT_SECRET', default='')
ZOOM_S2S_SECRET_TOKEN = config('ZOOM_S2S_SECRET_TOKEN', default='')

APPEND_SLASH = True

INSTALLED_APPS = [
    "daphne",
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    'storages',  # Add django-storages
    
    # Third Party Apps
    #add installations here
    "corsheaders",
    'rest_framework',
    'rest_framework.authtoken',  # Required for dj-rest-auth
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    "djoser",

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    'dj_rest_auth.registration',

    'crispy_forms',
    'crispy_tailwind',

    'rangefilter',
    'import_export',


    'nested_admin',
    'accounts',
    'api',
    'discussion',
    # 'elearning',
    'home',
    # 'super_admin',
    'student',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
    'accounts.middleware.SingleSessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'
# CORS settings
# CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True  # For development only, restrict in production

# ==========================
# CSRF Configuration
# ==========================
CSRF_TRUSTED_ORIGINS = [
    'https://api.k12nepal.com',
    'https://www.api.k12nepal.com',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://localhost:8000',
]

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access to CSRF cookie
CSRF_USE_SESSIONS = False  # Store CSRF token in cookie instead of session
CSRF_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'  # Chrome compatibility

# ==========================
# Session Configuration (Chrome Compatibility)
# ==========================
SESSION_COOKIE_SECURE = not DEBUG  # HTTPS only in production
SESSION_COOKIE_HTTPONLY = False  # Allow JavaScript access for OAuth
SESSION_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'  # Chrome cross-site compatibility
SESSION_SAVE_EVERY_REQUEST = True  # Ensure session persistence
SESSION_COOKIE_AGE = 31536000 * 10  # 10 years (effectively unexpirable)

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    'https://api.k12nepal.com',
    'https://*.k12nepal.com',
    'http://localhost:8000',
]

# Enhanced CORS headers for Chrome compatibility
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-forwarded-for',
    'x-forwarded-proto',
    'cache-control',
    'pragma',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
    'HEAD',
]

# Chrome-specific CORS settings
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# JWT Authentication settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        'accounts.authentication.VersionedJWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),  # 1 year (effectively unexpirable)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3650),  # 10 years (effectively unexpirable)
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
}


AUTH_USER_MODEL = 'accounts.CustomUser'  

# Frontend URL for password reset
FRONTEND_URL = 'http://localhost:3000' if DEBUG else 'https://k12nepal.com'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.larksuite.com'  # SMTP server from the image
EMAIL_USE_SSL = True  # Use SSL as specified (port 465 requires SSL, not TLS)
EMAIL_PORT = 465
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)

# Djoser settings for user registration and password reset
DJOSER = {
    "SERIALIZERS": {
        "user_create": "accounts.serializers.UserCreateSerializer",
        "user": "djoser.serializers.UserSerializer",
        "current_user": "djoser.serializers.UserSerializer",
    },
    "PASSWORD_RESET_CONFIRM_URL": "auth/reset-password-confirmation?uid={uid}&token={token}",
    "SEND_ACTIVATION_EMAIL": True, # Changed from False to True
    "SEND_CONFIRMATION_EMAIL": False,
    "LOGIN_FIELD": "email",
    "PASSWORD_RESET_CONFIRM_RETYPE": True,
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": True,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
    "LOGOUT_ON_PASSWORD_CHANGE": True,
    "ACTIVATION_URL": "auth/activate/{uid}/{token}", # Added this line
    "EMAIL": {
        "activation": "accounts.email.ActivationEmail",
        "password_reset": "accounts.email.PasswordResetEmail",
    },
}

# Site configuration for password reset emails
SITE_NAME = "Coding For Kids"
DOMAIN = "k12nepal.com"

# Django Sites Framework (required for allauth)
SITE_ID = 1

# Django Allauth settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Can be 'mandatory', 'optional', or 'none'
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

# Custom adapters
ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'

# Social account settings
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True

# Google OAuth settings (Chrome-compatible)
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
            'openid',  # Explicit OpenID Connect
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',  # Force account selection in Chrome
        },
        'OAUTH_PKCE_ENABLED': True,
        'VERIFIED_EMAIL': True,  # Trust Google's email verification
    }
}

# Google OAuth credentials (add these to your .env file)
GOOGLE_OAUTH2_CLIENT_ID = config('GOOGLE_OAUTH2_CLIENT_ID', default='')
GOOGLE_OAUTH2_CLIENT_SECRET = config('GOOGLE_OAUTH2_CLIENT_SECRET', default='')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Celery Configuration
CELERY_BROKER_URL = 'redis://:f22c7315242c4b87@localhost:6379/0'  # DB 0 for Celery
CELERY_RESULT_BACKEND = 'redis://:f22c7315242c4b87@localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json' 
CELERY_TIMEZONE = 'Asia/Kathmandu'
CELERY_ENABLE_UTC = True
USE_I18N = True
USE_L10N = True
USE_TZ = True  


# Background Tasks Configuration
BACKGROUND_TASK_RUN_ASYNC = True  # Run tasks asynchronously

CELERY_BEAT_SCHEDULE = {
    'notify_upcoming_live_classes_every_minute': {
        'task': 'api.tasks.notify_upcoming_live_classes',
        'schedule': 60.0,
    },
    'notify_upcoming_tests_every_minute': {
        'task': 'api.tasks.notify_upcoming_tests',
        'schedule': 60.0,
    },
}


CELERY_BROKER_URL = 'redis://:f22c7315242c4b87@localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://:f22c7315242c4b87@localhost:6379/0'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": ["redis://:f22c7315242c4b87@localhost:6379/2"],
            "capacity": 1500,
            "expiry": 10,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



# Database configuration
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',  # Path to the SQLite database file
#     }
# }

# Render provides DATABASE_URL, otherwise use individual POSTGRES_* vars
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
elif os.getenv('POSTGRES_HOST') and os.getenv('POSTGRES_HOST') not in ('', 'replace_me'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST'),
            'PORT': os.getenv('POSTGRES_PORT') or '5432',
            'OPTIONS': {
                'sslmode': os.getenv('POSTGRES_SSLMODE', 'require'),
                'client_encoding': 'UTF8',
                'connect_timeout': 30,
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



# Cloudflare R2 Settings (S3-compatible)
# Replace AWS settings with R2 settings
R2_ACCESS_KEY_ID = config('R2_ACCESS_KEY_ID')
R2_SECRET_ACCESS_KEY = config('R2_SECRET_ACCESS_KEY')
R2_STORAGE_BUCKET_NAME = config('R2_STORAGE_BUCKET_NAME')
R2_ENDPOINT_URL = config('R2_ENDPOINT_URL')  # Your R2 endpoint
R2_CUSTOM_DOMAIN = config('R2_CUSTOM_DOMAIN', default=None)  # Optional custom domain
CLOUDFLARE_WORKER_URL = config('CLOUDFLARE_WORKER_URL', default=None)  # Cloudflare Worker for secure R2 access

# Configure Django Storages for R2
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": R2_ACCESS_KEY_ID,
            "secret_key": R2_SECRET_ACCESS_KEY,
            "bucket_name": R2_STORAGE_BUCKET_NAME,
            "endpoint_url": R2_ENDPOINT_URL,
            "region_name": "auto",  # R2 uses "auto" for region
            "signature_version": "s3v4",
            "location": "media",
            "querystring_auth": True,
            "file_overwrite": False,
            "object_parameters": {
                'CacheControl': 'max-age=86400',
            },
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Media URL configuration for R2
# if R2_CUSTOM_DOMAIN:
MEDIA_URL = f'https://{R2_CUSTOM_DOMAIN}/media/'
# else:
    # MEDIA_URL = f'{R2_ENDPOINT_URL}/{R2_STORAGE_BUCKET_NAME}/media/'




# AWS S3 Settings (optional; prefer Cloudflare R2 above). Read from env only.
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', '')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = False
AWS_S3_VERIFY = True
AWS_QUERYSTRING_AUTH = True

# S3 Transfer Configuration for large file uploads
AWS_S3_TRANSFER_CONFIG = TransferConfig(
    multipart_threshold=1024 * 1024 * 25,  # 25MB
    multipart_chunksize=1024 * 1024 * 25,  # 25MB per chunk
    max_concurrency=10,
    use_threads=True
)

# Configure S3 as the default storage for media files
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com'
# R2_CUSTOM_DOMAIN = config('R2_CUSTOM_DOMAIN', default=None)
# MEDIA_URL = f'https://{R2_CUSTOM_DOMAIN}/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880000  # 5GB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880000  # 5GB
FILE_UPLOAD_TIMEOUT = 7200  # 2 hours

# AWS S3 additional settings
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",   # 1 day
    "ContentDisposition": "inline",    # optional — ensures browser displays instead of download
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field



# Configure logging for error tracking
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {  # Root logger
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
        },
        'api': {  # Logger for api app
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default
]

SITE_ID = 1  

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ==========================
# Email Configuration (Optional)
# ==========================

# If you plan to use Celery for background tasks
# CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
# CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = TIME_ZONE



# settings.py

# Configure Django Storages for S3
# STORAGES = {
#     "default": {
#         "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
#         "OPTIONS": {
#             "bucket_name": AWS_STORAGE_BUCKET_NAME,
#             "access_key": AWS_ACCESS_KEY_ID,
#             "secret_key": AWS_SECRET_ACCESS_KEY,
#             "region_name": AWS_S3_REGION_NAME,
#             "signature_version": AWS_S3_SIGNATURE_VERSION,
#             "location": "media",
#             "querystring_auth": AWS_QUERYSTRING_AUTH,
#             "file_overwrite": AWS_S3_FILE_OVERWRITE,
#         },
#     },
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
#     },
# }

# CKEditor 5 Configuration
customColorPalette = [
    {"color": "hsl(4, 90%, 58%)", "label": "Red"},
    {"color": "hsl(340, 82%, 52%)", "label": "Pink"},
    {"color": "hsl(291, 64%, 42%)", "label": "Purple"},
    {"color": "hsl(262, 52%, 47%)", "label": "Deep Purple"},
    {"color": "hsl(231, 48%, 48%)", "label": "Indigo"},
    {"color": "hsl(207, 90%, 54%)", "label": "Blue"},
]

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://:f22c7315242c4b87@localhost:6379/1',  # DB 1 for Cache
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'SOCKET_TIMEOUT': 5,
            'IGNORE_EXCEPTIONS': True,
        }
    }
}

# Cache timeout for session tokens (10 years - effectively unexpirable)
SESSION_TOKEN_TIMEOUT = 31536000 * 10

# OnePG Payment Gateway Settings (optional; defaults allow app to run without OnePG)
ONEPG_MERCHANT_ID = config('ONEPG_MERCHANT_ID', default='')
ONEPG_MERCHANT_NAME = config('ONEPG_MERCHANT_NAME', default='')
ONEPG_API_USERNAME = config('ONEPG_API_USERNAME', default='')
ONEPG_API_PASSWORD = config('ONEPG_API_PASSWORD', default='')
ONEPG_SECRET_KEY = config('ONEPG_SECRET_KEY', default='')
ONEPG_API_BASE_URL = config('ONEPG_API_BASE_URL', default='')
ONEPG_GATEWAY_URL = config('ONEPG_GATEWAY_URL', default='')

CLEANUP_EXPIRED_PROGRAMS_INTERVAL = 0


# OR allow all users (default behavior)
CLEANUP_EXPIRED_PROGRAMS_USER_TYPES = None

NPQR_USER_ID = config('NPQR_USER_ID', default='')
NPQR_API_USERNAME = config('NPQR_API_USERNAME', default='')
NPQR_API_PASSWORD = config('NPQR_API_PASSWORD', default='')
NPQR_API_BASE_URL = config('NPQR_API_BASE_URL', default='')
NPQR_ACQUIRER_ID = config('NPQR_ACQUIRER_ID', default='')
NPQR_MERCHANT_ID = config('NPQR_MERCHANT_ID', default='')
NPQR_MERCHANT_NAME = config('NPQR_MERCHANT_NAME', default='')
NPQR_MERCHANT_CATEGORY_CODE = config('NPQR_MERCHANT_CATEGORY_CODE', default='')
NPQR_MERCHANT_COUNTRY = config('NPQR_MERCHANT_COUNTRY', default='')
NPQR_MERCHANT_CITY = config('NPQR_MERCHANT_CITY', default='')
NPQR_MERCHANT_POSTAL_CODE = config('NPQR_MERCHANT_POSTAL_CODE', default='')
NPQR_MERCHANT_LANGUAGE = config('NPQR_MERCHANT_LANGUAGE', default='')
NPQR_TRANSACTION_CURRENCY = config('NPQR_TRANSACTION_CURRENCY', default='NPR')
NPI_PFX_FILE = config('PFX_FILE_PATH', default='')
NPI_PFX_CODE = config('PFX_CODE', default='')
